"""
Django settings for cats project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from . import secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SERVER_ROOT = Path(secrets.SERVER_ROOT)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'stronghold',
    'bootstrap4',
    'easy_thumbnails',
    #'import_export',
    #'haystack',

    'cat',
    'campus',
    'file',
]

MIDDLEWARE = [
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'stronghold.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'cats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'libraries': {
                'setting': 'utilties.templatetags',
            },
        },
    },
]

WSGI_APPLICATION = 'cats.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': SERVER_ROOT / 'django.log',
        },
        'server_chan': {
            'level': 'ERROR',
            'class': 'utilties.ServerChanHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'server_chan'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': secrets.DB_NAME,
        'USER': secrets.DB_USER,
        'PASSWORD': secrets.DB_PASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'campus.User'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = SERVER_ROOT / 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


MEDIA_URL = '/media/'
MEDIA_ROOT = SERVER_ROOT / 'media/'


#
# 3rd party settings
#


# Stronghold
# https://github.com/mgrouchy/django-stronghold

STRONGHOLD_DEFAULTS = False
STRONGHOLD_PUBLIC_NAMED_URLS = (
    'index',
    'about',
    'user-login',
)


# easy_thumbnail
# https://django-filer.readthedocs.io/en/latest/installation.html

THUMBNAIL_DEBUG = False
THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_ALIASES = {
    '': {
        'avatar-lg': {
            'size': (300, 300),
            'crop': True
        },
        'avatar-sm': {
            'size': (40, 40),
            'crop': True
        },
        'photo-thumbnail': {
            'size': (200, 200),
            'crop': True
        },
        'main-card-image': {
            'size': (512, 288),
            'crop': True
            }
    }
}

# Haystack
# https://django-haystack.readthedocs.io/en/master/tutorial.html
# 
# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
#         'PATH': BASE_DIR / 'whoosh_index',
#     },
# }


#
# Project settings
# 

# 默认猫猫头像的 static 链接 str
DEFAULT_CAT_AVATAR = 'image/default_avatar.jpg'

# 用来向微信推送错误日志的服务密钥，不启用 utilties 中的相应 Handler 则可以不用理睬
# 详见 https://sc.ftqq.com
SERVER_CHAN_SCKEY = secrets.SERVER_CHAN_SCKEY

# 使用高德地图服务需要的 Key
# 详见 https://lbs.amap.com/
AMAP_KEY = secrets.AMAP_KEY
